sudo: required
services:
- docker

cache:
  bundler: true
  directories:
  - spec/fixtures/artifacts
  - spec/fixtures/modules

language: ruby

jobs:
  include:
   - stage: intake
     script: bundle exec rake intake
     matrix:
       include:
        - env: PUPPET_VERSION='~> 3.8'
        - env: PUPPET_VERSION='~> 4.10'
   - stage: acceptance
     before_script: bundle exec rake spec_prep
     script: bundle exec rake beaker:$PLATFORM
     matrix:
       include:
        - env: PLATFORM=integration
        - env: PLATFORM=centos-6-x64 PUPPET_INSTALL_TYPE=foss
        - env: PLATFORM=centos-6-x64
        - env: PLATFORM=centos-7-x64 PUPPET_INSTALL_TYPE=foss
        - env: PLATFORM=centos-7-x64
        - env: PLATFORM=debian-7-x64
        - env: PLATFORM=debian-8-x64
        - env: PLATFORM=ubuntu-server-1404-x64 PUPPET_INSTALL_TYPE=foss
        - env: PLATFORM=ubuntu-server-1404-x64
        - env: PLATFORM=ubuntu-server-1604-x64
        - env: PLATFORM=opensuse-42-x64 PUPPET_INSTALL_TYPE=foss
        - env: PLATFORM=oracle-6-x64
        - env: PLATFORM=oracle-7-x64

env:
- PUPPET_VERSION='~> 3.8'
- PUPPET_VERSION='~> 4.10'
- PLATFORM=integration
- PLATFORM=centos-6-x64 PUPPET_INSTALL_TYPE=foss
- PLATFORM=centos-6-x64
- PLATFORM=centos-7-x64 PUPPET_INSTALL_TYPE=foss
- PLATFORM=centos-7-x64
- PLATFORM=debian-7-x64
- PLATFORM=debian-8-x64
- PLATFORM=ubuntu-server-1404-x64 PUPPET_INSTALL_TYPE=foss
- PLATFORM=ubuntu-server-1404-x64
- PLATFORM=ubuntu-server-1604-x64
- PLATFORM=opensuse-42-x64 PUPPET_INSTALL_TYPE=foss
- PLATFORM=oracle-6-x64
- PLATFORM=oracle-7-x64

notifications:
  slack:
    secure: T1FO+ttrJNH+bXmNR6349qcttG68Qr1xmMqVVRnUr7+129GQO5174Z8MFC8ck0qOCZGHO7GCNO5seNFflrjF/5EKbdkmVnqhf9gVa9kN7I4psMzxJX9bp29xJA6m3wA4VqCosDKVFSfilDZujAblWT+KDHZLjP8sEWEnHPvCjf69S2XDQEWUoxZan5V9IJQas4XR+hMdIZTA3ChVrEyqRfeehAZImbAr/LH8zChZaTdHZQY7p2rN3+qVNi3+GISV9fNPpOCynnX/ACbdUaRt3+1etxGGaQMPzGmTejN3VlMw4OZRXImb6HQ2rXE+fNCASXiKiwylxTbriQsS0dFv4skxH03YlYM8pqaBpeIOwzf4n45tTzdAQZJMC5cOb+RvwS7qkAwuaVlVxiiA+MWRG/UcFpWS+iNn4KEKxbpBjYP8X1JIP9DlHLME7DNMM2pePv9X6ZjY6eDhVM1gbKi77dXOo5y2Sp0ru8QkLpIKFVXS01O+x7oDHHv2Osvih0jNMgM66Byso3KJYJ6EJ0D2/3Q9ZNpVM4CMuIY5pBQfXf691zqkBHI6JUnU6VMw97cH0k6Gq0ypZoW5trXdnRC5aEg4jKKid84zKmAeTpj/iMuagyb/a5msJstIVboynRtfDHR0J8WWhfSU2wzqKAb6L66iyRe62Fe8OGzLhk2+KNU=
